import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return(
    <div>
       <title>PvPAcademy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Component {...pageProps} />
    </div>
  )
}

export default MyApp
